### ISSUE TITLE
why are .cpp files installed

### ISSUE THREAD

**Issue by KrisThielemans** [paskino/libace-conda#10]
We copy .cpp files to `include` [here](https://github.com/paskino/libace-conda/blob/3e1e7ce2c6ae5caeee5a13c8f56e34f2ddc14b7b/build_ace.sh#L124). Is that really needed?

**Comment by paskino** [comment]
Probably not. Well spotted

**Comment by jwillemsen** [comment]
You do need to install all _T.cpp files which are the template sources
